name: GitHub Pages

on:
  push:
    branches:
      - master
    paths: 
      - src/**

jobs:  
  publish:
    runs-on: ubuntu-20.04    
    container:
      image: python:2.7.18-buster
    steps:      
      - name: Checkout 🛎️
        uses: actions/checkout@v4.1.1
        with:
          sparse-checkout: false
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the version of Node.js you want to use
      
      - name: Install gatsby required dependencies
        run: npm install
        
      - name: Generate deployment build
        run: npm run build

      - name: Create CNAME record
        run: echo josemariabecerril.com > ./public/CNAME
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./public

        
